// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlddvddmawlqtvqefwav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsZGR2ZGRtYXdscXR2cWVmd2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzAxODYsImV4cCI6MjA2MTcwNjE4Nn0.aNyvRI8Q-o5HYGeeos18gqTxZK_UIw_9iby2DmHP04c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);